# ===========================================================================
# Example Docker Compose file
# ===========================================================================
#
# Purpose:
# --------
#
# This file is an example Docker Compose configuration for self hosting
# Maybe Django on your local machine or on a cloud VPS.
#
# The configuration below is a "standard" setup that works out of the box,
# but if you're running this outside of a local network, it is recommended
# to set the environment variables for extra security.
#
# Setup:
# ------
#
# To run this, copy this file to `compose.yml` and configure environment variables:
#
# cp compose.example.yml compose.yml
# # Edit compose.yml with your settings
#
# Then run:
#
# docker compose up -d
#
# Troubleshooting:
# ----------------
#
# If you run into problems, you should open a Discussion here:
#
# https://github.com/maybe-finance/maybe/discussions/categories/general
#

x-db-env: &db_env
  POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-maybe_password}
  POSTGRES_DB: ${POSTGRES_DB:-maybe_django}

x-django-env: &django_env
  <<: *db_env
  SECRET_KEY: ${SECRET_KEY:-django-insecure-change-me-in-production}
  DEBUG: ${DEBUG:-True}
  DB_HOST: db
  DB_PORT: 5432
  DB_NAME: ${POSTGRES_DB:-maybe_django}
  DB_USER: ${POSTGRES_USER:-maybe_user}
  DB_PASSWORD: ${POSTGRES_PASSWORD:-maybe_password}
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-storage:/app/storage
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      <<: *django_env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - maybe_net
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      <<: *django_env
    networks:
      - maybe_net
    command: celery -A maybe_django worker -l info
    working_dir: /app

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      <<: *django_env
    networks:
      - maybe_net
    command: celery -A maybe_django beat -l info
    working_dir: /app

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *db_env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - maybe_net

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - maybe_net

volumes:
  app-storage:
  postgres-data:
  redis-data:

networks:
  maybe_net:
    driver: bridge
