# Generated by Django 5.2.8 on 2025-11-29 12:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(help_text='Ticker symbol (e.g., PETR4.SA for B3)', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(default='BR', help_text='ISO country code', max_length=2)),
                ('exchange_mic', models.CharField(blank=True, help_text='Market Identifier Code', max_length=10)),
                ('exchange_acronym', models.CharField(blank=True, max_length=20)),
                ('exchange_operating_mic', models.CharField(blank=True, max_length=10)),
                ('logo_url', models.URLField(blank=True)),
                ('offline', models.BooleanField(default=False)),
                ('failed_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('failed_fetch_count', models.IntegerField(default=0)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'securities',
                'db_table': 'securities',
                'indexes': [models.Index(fields=['country_code'], name='securities_country_94d292_idx'), models.Index(fields=['exchange_operating_mic'], name='securities_exchang_8e67d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='finance.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investments.security')),
            ],
            options={
                'db_table': 'holdings',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'security', 'date'], name='holdings_account_936517_idx')],
                'unique_together': {('account', 'security', 'date', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='investments.security')),
            ],
            options={
                'db_table': 'security_prices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['security', 'date'], name='security_pr_securit_c89bf2_idx')],
                'unique_together': {('security', 'date', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=4, help_text='Positive for buy, negative for sell', max_digits=19)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=4, help_text='qty * price (negative for buy, positive for sell)', max_digits=19)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='finance.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='investments.security')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['account', 'security', 'date'], name='trades_account_c44eb5_idx')],
            },
        ),
    ]
