title: Feature Request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Maybe Django!  Please follow the template below to submit your feature request.  Be sure to search existing discussions to avoid duplicates.
  - type: textarea
    attributes:
      label: Describe the feature
      description: Provide a clear and concise description of the feature you would like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is this feature important?
      description: Tell us what specific problem(s) this feature solves for you or other users.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context, screenshots, and relevant links
      description: Provide additional info to help us evaluate whether this feature is a good fit for the product.
