# Generated by Django 5.2.8 on 2025-11-29 12:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('accountable_type', models.CharField(choices=[('depository', 'Depository'), ('investment', 'Investment'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('property', 'Property'), ('vehicle', 'Vehicle'), ('crypto', 'Crypto'), ('other_asset', 'Other Asset'), ('other_liability', 'Other Liability')], max_length=20)),
                ('accountable_data', models.JSONField(blank=True, default=dict, help_text='Accountable-specific data')),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('cash_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('pending_deletion', 'Pending Deletion')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('cash_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('start_cash_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('start_non_cash_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('cash_inflows', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('cash_outflows', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('non_cash_inflows', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('non_cash_outflows', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('net_market_flows', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('cash_adjustments', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('non_cash_adjustments', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('flows_factor', models.IntegerField(default=1, help_text='1 for assets, -1 for liabilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='finance.account')),
            ],
            options={
                'db_table': 'balances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('budgeted_spending', models.DecimalField(blank=True, decimal_places=4, help_text='Total budgeted spending for the month', max_digits=19, null=True)),
                ('expected_income', models.DecimalField(blank=True, decimal_places=4, help_text='Expected income for the month', max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#6172F3', max_length=7)),
                ('classification', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10)),
                ('lucide_icon', models.CharField(default='shapes', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budgeted_spending', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='finance.budget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='finance.category')),
            ],
            options={
                'db_table': 'budget_categories',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=19)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_rates',
                'indexes': [models.Index(fields=['from_currency'], name='exchange_ra_from_cu_927258_idx'), models.Index(fields=['to_currency'], name='exchange_ra_to_curr_dda85c_idx')],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_type', models.CharField(choices=[('transaction', 'Transaction')], default='transaction', max_length=20)),
                ('effective_date', models.DateField(blank=True, help_text='Date from which rule applies (null = all dates)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('set_transaction_category', 'Set Transaction Category'), ('set_transaction_tags', 'Set Transaction Tags'), ('set_transaction_merchant', 'Set Transaction Merchant'), ('set_transaction_name', 'Set Transaction Name')], max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='finance.rule')),
            ],
            options={
                'db_table': 'rule_actions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(choices=[('transaction_name', 'Transaction Name'), ('transaction_amount', 'Transaction Amount'), ('transaction_merchant', 'Transaction Merchant'), ('compound', 'Compound')], max_length=50)),
                ('operator', models.CharField(choices=[('like', 'Contains'), ('=', 'Equal to'), ('>', 'Greater than'), ('>=', 'Greater or equal to'), ('<', 'Less than'), ('<=', 'Less than or equal to'), ('or', 'OR'), ('and', 'AND')], max_length=10)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_conditions', to='finance.rulecondition')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='finance.rule')),
            ],
            options={
                'db_table': 'rule_conditions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#e99537', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('excluded', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('standard', 'Standard'), ('funds_movement', 'Funds Movement'), ('cc_payment', 'Credit Card Payment'), ('loan_payment', 'Loan Payment'), ('one_time', 'One Time')], default='standard', max_length=20)),
                ('installment_current', models.IntegerField(blank=True, help_text='Current installment number', null=True)),
                ('installment_total', models.IntegerField(blank=True, help_text='Total number of installments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.merchant')),
                ('original_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.transaction')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='finance.tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='finance.transaction')),
            ],
            options={
                'db_table': 'taggings',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inflow_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflow_transfers', to='finance.transaction')),
                ('outflow_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflow_transfers', to='finance.transaction')),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('reconciliation', 'Reconciliation'), ('current_anchor', 'Current Anchor')], default='reconciliation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='finance.account')),
            ],
            options={
                'db_table': 'valuations',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'status'], name='accounts_user_id_e05c06_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'accountable_type'], name='accounts_user_id_9ae172_idx'),
        ),
        migrations.AddIndex(
            model_name='balance',
            index=models.Index(fields=['account', 'date'], name='balances_account_bd6b24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('account', 'date', 'currency')},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'start_date'], name='budgets_user_id_5fe0ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['budget', 'category'], name='budget_cate_budget__5aa1b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='merchant',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['user', 'resource_type'], name='rules_user_id_5ddf84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='transaction_account_f34883_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='transaction_date_7edf95_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['kind'], name='transaction_kind_b2fbf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontag',
            unique_together={('transaction', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together={('inflow_transaction', 'outflow_transaction')},
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['account', 'date'], name='valuations_account_5a8238_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valuation',
            unique_together={('account', 'date', 'kind')},
        ),
    ]
