# Generated by Django 5.2.8 on 2025-12-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecondition',
            name='operator',
            field=models.CharField(choices=[('like', 'Contains'), ('=', 'Equal to'), ('regex', 'Matches pattern (regex)'), ('>', 'Greater than'), ('>=', 'Greater or equal to'), ('<', 'Less than'), ('<=', 'Less than or equal to'), ('or', 'OR'), ('and', 'AND')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
